##Practica - Modulo 1-Data Structures

Ejercicio1 : Crea una lista con los multiplos entre 1 y 100 usando comprehension

In [ ]:
my_list = [x for x in range(1,101)]
print(my_list)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100]


##Ejercicio 2 Dado el direccionario de
datos = {'a':10,'b':25,'c':7,'d':18}

###a)Crea una lista con las claves cuyo valor sea mayor a 12
###b)Crea un nuevo diccionario con esas claves y sus valores al cuadrado



In [ ]:
#a
datos = {'a':10,'b':25,'c':7,'d':18}
value_key = []
for clave,valor in datos.items():
  if valor > 12:
    value_key += [clave]
print(value_key)
#b
new_dicc = {}
for clave,valor in datos.items():
  if clave in value_key:
    new_dicc[clave] = valor
    new_dicc[clave] = valor**2
print(new_dicc)



['b', 'd']
{'b': 625, 'd': 324}


###Ejercicio 3: Define una función 'resumen(lista)' que retorne un diccionario con longitud, suma, promedio, mínimo y máximo de la lista

In [ ]:
def resumen(lista):
  dicc = {}
  dicc['longitud'] = len(lista)
  dicc['suma'] = sum(lista)
  dicc['promedio'] = sum(lista)/len(lista)
  dicc['minimo'] = min
  dicc['maximo'] = max
  return dicc

###Ejercicio 4: Usa map() para aplicar la función potencia(x, 3) a la lista [1,2,3,4,5].

In [ ]:
lista = [1,2,3,4,5]

resultado = list(map(lambda x: x**3,lista))
print(resultado)

[1, 8, 27, 64, 125]


##Practica - Modulo 2-Atributes and Creation of Arrays

###Ejercicio 1: Crea los siguientes arrays y verifica sus atributos (shape, dtype, ndim)
###a) Vector con enteros del 1 al 20.
###b) Matriz de ceros de 5 filas y 3 columnas.
###c) 10 puntos igualmente espaciados entre -1 y 1 con linspace.

In [ ]:
import numpy as np
#a
vector_test = np.array([x for x in range(1,21)])
print(vector_test)
#shape
print("Shape", vector_test.shape)
#dtype
print("Dtype",vector_test.dtype)
#ndim
print("Ndim",vector_test.ndim)
#b
matrix_text = np.zeros((5,3))
print(matrix_text)
#shape
print("Shape", matrix_text.shape)
#dtype
print("Dtype",matrix_text.dtype)
#ndim
print("Ndim",matrix_text.ndim)
#c
space_points = np.linspace(-1,1,10)
print(space_points)
#shape
print("Shape", space_points.shape)
#dtype
print("Dtype",space_points.dtype)
#ndim
print("Ndim",space_points.ndim)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Shape (20,)
Dtype int64
Ndim 1
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Shape (5, 3)
Dtype float64
Ndim 2
[-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
  0.33333333  0.55555556  0.77777778  1.        ]
Shape (10,)
Dtype float64
Ndim 1


##Ejercicio 2: Con np.random.seed(99) crea una matriz 4×4 de enteros entre 0 y 50.
##Imprime: shape, dtype, tamaño en bytes (nbytes) y el elemento [2,3].

In [ ]:
np.random.seed(99)

matrix_random = np.random.randint(0,50,(4,4))
print(matrix_random)
#shape
print("Shape",matrix_random.shape)
#dtype
print("Dtype",matrix_random.dtype)
#tamaño en bytes
print("Nbytes",matrix_random.nbytes)
#elemento [2,3]
print(matrix_random[2,3])

[[ 1 35 40  9]
 [40 18  4  5]
 [ 1 23 35 49]
 [ 1 48 29 38]]
Shape (4, 4)
Dtype int64
Nbytes 128
49


##Ejercicio 3: ¿Cuál es la diferencia de dtype entre np.array([1,2,3]) y np.array([1.0,2.0,3.0])? Verifica con código

In [ ]:
array1 = np.array([1,2,3])
array2 = np.array([1.0,2.0,3.0])
print(array1.dtype)#int64
print(array2.dtype)#float64


int64
float64


###Ejercicio 4: Crea una matriz identidad 5×5 y verifica que la suma de su diagonal es igual a 5 (usa np.trace()).

In [ ]:
matrix_identity = np.eye(5)
print(matrix_identity)
#verify
print(np.trace(matrix_identity))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
5.0


##Practica - Modulo 3- Indexing, Slicing, Reshape

###Ejercicio 1: Dado A = np.arange(1, 26).reshape(5, 5)
###a) Extrae la sub-matriz de las 3 últimas filas y las 3 primeras columnas.
###b) Extrae la segunda columna completa.
###c) Extrae los elementos de los ángulos (esquinas) de la matriz

In [ ]:
import numpy as np
A = np.arange(1,26).reshape(5,5)
print(A)
#a slicing
sub_matrix = A[2::,::2].copy()
print(sub_matrix)
#b fancy indexing
second_column = A[::,1].copy()
print(second_column)
#c fancy indexing
corners_matrix = A[[0,4],:][:,[0,4]].copy()
print(corners_matrix)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[[11 13 15]
 [16 18 20]
 [21 23 25]]
[ 2  7 12 17 22]
[[ 1  5]
 [21 25]]


###Ejercicio 2: Con la misma matriz A:
###a) Crea una máscara booleana para los valores mayores a 12.
###b) Reemplaza esos valores por -1 en una copia del array.
###c) Usa np.where para reemplazar impares por 0 y mantener los pares

In [ ]:
A = np.arange(1,26).reshape(5,5)
#a mascara booleana
mask = A > 12
print(mask)
values = A[mask]
print(values)
#b modify values as -1 in an copy mask
values_copy = A.copy()
values_copy[values_copy > 12] = -1
print(values_copy)
#c np.where to replace odds as 0 and keep evens
new_array = np.where(A%2 != 0,0,A)
print(new_array)


[[False False False False False]
 [False False False False False]
 [False False  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]
[13 14 15 16 17 18 19 20 21 22 23 24 25]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]]
[[ 0  2  0  4  0]
 [ 6  0  8  0 10]
 [ 0 12  0 14  0]
 [16  0 18  0 20]
 [ 0 22  0 24  0]]


###Ejercicio 3: Crea un vector de 24 elementos con arange(24).
###Reorganízalo en:
###(a) matriz 6×4,
###(b) tensor 2×3×4,
###(c) vector fila 1×24

In [ ]:
elements = np.arange(24) #0-23
print(elements)
#a reshape matrix 6x4
m6x4 = elements.reshape(6,4)
print(m6x4)
#b tensor 2x3x4
tensor = elements.reshape(2,3,4)
print(tensor)
#c vector fila 1 x24
vFila = elements.reshape(1,24)
print(vFila)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]]


###Ejercicio 4: Demuestra la diferencia vista vs. copia: modifica un elemento en un slice y verifica que el array original también cambia.

In [ ]:
import numpy as np
diference = np.array([
    [1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]])
#copy of all array twice
vista = diference[::]
copia = diference[::].copy()
#modify an element with slice
vista[0, 3] = 18
copia[0, 3] = 19
#verify original array changed
print(diference)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3 18]
 [ 5  6  7  8]
 [ 9 10 11 12]]


##Practica - Modulo 4- Operaciones Numericas y Manejo de Datos

###Ejercicio 1: Crea una matriz 5×4 de enteros aleatorios entre 1 y 100 (seed=7).
###a) Calcula la media, máximo y mínimo de cada columna.
###b) Calcula la suma acumulada de la primera fila.
##c) Normaliza la matriz para que cada columna tenga valores entre 0 y 1.Fórmula: (x - min_col) / (max_col - min_col)

In [ ]:
import numpy as np
np.random.seed(7)

M5x4= np.random.randint(1,100,(5,4))
print(M5x4)
#a
#media
media = M5x4.mean(axis=0)
print("Media: ",media)
#max
max = M5x4.max(axis=0)
print("Max: ",max)
#min
min = M5x4.min(axis=0)
print("Min: ",min)
#b suma acumulada de primera fila
suma_acumulada = np.cumsum(M5x4[0])
print("Suma acumulada de la primera fila: ", suma_acumulada)
#c Normaliza la matriz para que cada columna tenga valores entre 0 y 1.
normalized_M5x4 = (M5x4 - min) / (max - min)
print("Matriz normalizada:")
print(normalized_M5x4)

[[48 69 26 68]
 [84 24 93 58]
 [15 24 73 90]
 [43 91  9 40]
 [69 49  8 45]]
Media:  [51.8 51.4 41.8 60.2]
Max:  [84 91 93 90]
Min:  [15 24  8 40]
Suma acumulada de la primera fila:  [ 48 117 143 211]
Matriz normalizada:
[[0.47826087 0.67164179 0.21176471 0.56      ]
 [1.         0.         1.         0.36      ]
 [0.         0.         0.76470588 1.        ]
 [0.4057971  1.         0.01176471 0.        ]
 [0.7826087  0.37313433 0.         0.1       ]]


###Ejercicio 2: Usando broadcasting:
###a) Crea un vector fila [1,2,3,4] y un vector columna [[10],[20],[30]].
###b) Suma ambos vectores y explica el shape del resultado.

In [ ]:
#a
vf = np.array([1,2,3,4]) #shape(4,) -> (1,4)
print("Vector fila",vf)
vc = np.array([[10],[20],[30]]) #shape(3,1)
print("Vector columna",vf)
#b
print(vf + vc) # shape (3,4)

Vector fila [1 2 3 4]
Vector columna [1 2 3 4]
[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


###Ejercicio 3: Con el array de notas y nombres del ejemplo de argsort:
###a) ¿Cuántos estudiantes tienen nota mayor al promedio? (usa máscara booleana)
###b) Imprime solo los nombres de esos estudiantes

In [ ]:
nombres = np.array(['Carlos','Ana','Diana','Pedro','Eva','Luis'])
notas = np.array([75, 92, 88, 61, 95, 78])
#a est nota>prom
mask2 = notas > np.mean(notas)
print(mask2)

resultado_est = nombres[mask2]
print(resultado_est)


[False  True  True False  True False]
['Ana' 'Diana' 'Eva']


###Ejercicio 4: Crea dos matrices 3×4 y concaténalas vertical y horizontalmente.
###Luego divide el resultado vertical en 3 partes iguales con vsplit.

In [ ]:
#matriz 1
m1 = np.random.randint(1,100,(3,4))
print(m1)

#matriz 2
m2_f = np.arange(12)
m2 = m2_f.reshape(3,4)
print(m2)
#concatenar
m1_m2 = np.concatenate((m1,m2),axis=0)
print(m1_m2)
#split
partes = np.vsplit(m1_m2,3)
print(partes)


[[11 36 65 62]
 [ 8 24 93 97]
 [22 36 98 68]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[11 36 65 62]
 [ 8 24 93 97]
 [22 36 98 68]
 [ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[array([[11, 36, 65, 62],
       [ 8, 24, 93, 97]]), array([[22, 36, 98, 68],
       [ 0,  1,  2,  3]]), array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])]
